document edge markers
hedhyw/rex pull request #52
Opened 2022-10-05 18:00 UTC by ryzheboka

#47

2022-10-06 01:26 UTC, hedhyw requested changes

2022-10-06 01:26 UTC, hedhyw commented on _docs/library.md
> +Chars.NotASCIIWordBoundary()     // `\B`
```suggestion
rex.Chars.ASCIIWordBoundary()        // `\b`
rex.Chars.NotASCIIWordBoundary()     // `\B`
```

2022-10-08 08:35 UTC, ryzheboka commented on _docs/library.md
> +Chars.NotASCIIWordBoundary()     // `\B`
Done :)

2022-10-08 11:09 UTC, hedhyw approved these changes

2022-10-08 11:10 UTC, merged